/*
 * @Descripttion:
 * @version:
 * @Author: bicitech-fed
 * @Date: 2022-08-31 16:37:13
 * @LastEditors: bicitech-fed
 * @LastEditTime: 2022-09-17 15:23:19
 */
export const BOARD_SHARE_INFO = 'BOARD_SHARE_PWD';

export const NEW_BOARD_INDUSTRY_CONVEYOR = [121, '传送带'];
export const NEW_BOARD_INDUSTRY_STORAGE_SILO = [122, '储料罐'];
export const NEW_BOARD_INDUSTRY_CHEMICAL_INDUSTRY = [123, '化工'];
export const NEW_BOARD_INDUSTRY_MATERIAL_HANDLING = [124, '原料处理'];
export const NEW_BOARD_INDUSTRY_REACTOR = [125, '反应器'];
export const NEW_BOARD_INDUSTRY_DIRECTOR = [126, '控制器'];
export const NEW_BOARD_INDUSTRY_MACHINE_WORK = [127, '机械加工'];
export const NEW_BOARD_INDUSTRY_PUMP = [128, '泵'];
export const NEW_BOARD_INDUSTRY_ELECTRIC_MACHINERY = [129, '电机'];
export const NEW_BOARD_INDUSTRY_CIRCUITRY = [130, '电路图'];
export const NEW_BOARD_INDUSTRY_PIPELINE = [131, '管道'];
export const NEW_BOARD_INDUSTRY_VENT_LINE = [132, '通风管道'];
export const NEW_BOARD_INDUSTRY_MINE = [133, '采矿'];
export const NEW_BOARD_INDUSTRY_STEEL_INDUSTRY = [134, '钢铁行业'];
export const NEW_BOARD_INDUSTRY_BOILER = [135, '锅炉'];
export const NEW_BOARD_INDUSTRY_KLEP = [136, '阀门'];
// 公共路由跳转 tabParams 参数
export const RouteTabtabParamsState = {
  isClose: true,
};

export const industry_List = [
  NEW_BOARD_INDUSTRY_CONVEYOR,
  NEW_BOARD_INDUSTRY_STORAGE_SILO,
  NEW_BOARD_INDUSTRY_CHEMICAL_INDUSTRY,
  NEW_BOARD_INDUSTRY_MATERIAL_HANDLING,
  NEW_BOARD_INDUSTRY_REACTOR,
  NEW_BOARD_INDUSTRY_DIRECTOR,
  NEW_BOARD_INDUSTRY_MACHINE_WORK,
  NEW_BOARD_INDUSTRY_PUMP,
  NEW_BOARD_INDUSTRY_ELECTRIC_MACHINERY,
  NEW_BOARD_INDUSTRY_CIRCUITRY,
  NEW_BOARD_INDUSTRY_PIPELINE,
  NEW_BOARD_INDUSTRY_VENT_LINE,
  NEW_BOARD_INDUSTRY_MINE,
  NEW_BOARD_INDUSTRY_STEEL_INDUSTRY,
  NEW_BOARD_INDUSTRY_BOILER,
  NEW_BOARD_INDUSTRY_KLEP,
];
